apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  selector:
    app.kubernetes.io/name: hello-world
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 3333
      protocol: TCP
