apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: hello-world
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hello-world
    spec:
      containers:
        - name: http-srv
          image: localhost/hello-world:v0.1.0
          args:
            - -addr=0.0.0.0:3333
          envFrom:
            - configMapRef:
                name: env
          ports:
            - containerPort: 3333
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: 128Mi
